name: Setup for deploy
description: This sets up the build environment, logs into Azure, and sets the short SHA variable

inputs:
  build-environment:
    description: node or dotnet allowed
    required: true
  client-id:
    description: Azure clientId
    required: true
  client-secret:
    description: Azure clientSecret
    required: true
  subscription-id:
    description: Azure subscriptionId
    required: true
  tenant-id:
    description: Azure tenantId
    required: true
  dotnet-version:
    description: Desired .NET version if using dotnet
    required: false
  node-version:
    description: Desired Node version if using Node
    required: false

outputs:
  short-sha:
    description: Seven character version of SHA
    value: ${{ steps.short-sha.outputs.short-sha }}

runs:
  using: "composite"
  steps:
    - name: Fail if invalid input
      if: inputs.build-environment != 'node' && inputs.build-environment != 'dotnet'
      run: exit 1
      shell: bash

    - name: Setup Node
      if: inputs.build-environment == 'node' 
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        
    - name: Setup .NET
      if: inputs.build-environment == 'dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Login to Azure
      uses: Azure/login@v1.1
      with:
        creds: '{"clientId":"${{ inputs.client-id }}","clientSecret":"${{ inputs.azure-client-secret }}","subscriptionId":"${{ inputs.subscription-id }}","tenantId":"${{ inputs.tenant-id }}"}'

    - name: Calculate github short sha
      id: short-sha
      run: echo "::set-output name=short-sha::$(git rev-parse --short HEAD)"
      shell: bash
