name: Setup for deploy
description: This sets up the build environment, logs into Azure, and sets the short SHA variable

inputs:
  client-id:
    description: Azure clientId
    required: true
  client-secret:
    description: Azure clientSecret
    required: true
  language:
    description: node or dotnet allowed
    required: true
  language-version:
    description: Desired version in quotes
    required: true
  nuget-token:
    description: Nuget token if private packages
    required: false
    default: 'none'
  subscription-id:
    description: Azure subscriptionId
    required: true
  tenant-id:
    description: Azure tenantId
    required: true

outputs:
  short-sha:
    description: Seven character version of SHA
    value: ${{ steps.short-sha.outputs.short-sha }}

runs:
  using: "composite"
  steps:
    - name: Fail if invalid input
      if: inputs.language != 'node' && inputs.language != 'dotnet'
      run: exit 1
      shell: bash

    - name: Setup Node
      if: inputs.language == 'node' 
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.language-version }}
        
    - name: Setup .NET
      if: inputs.language == 'dotnet' && inputs.nuget-token == 'none'
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.language-version }}
        
    - name: Setup .NET with token
      if: inputs.language == 'dotnet' && inputs.nuget-token != 'none'
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.language-version }}
        source-url: https://nuget.pkg.github.com/arundo/index.json
      env:
        NUGET_AUTH_TOKEN: ${{inputs.nuget-token}}
        
    - name: Install Nuget configuration so docker can use Arundo packages
      if: inputs.language == 'dotnet' && inputs.nuget-token != 'none'
      uses: finnp/create-file-action@master
      env:
        FILE_NAME: "nuget.config"
        FILE_DATA: "<?xml version=\"1.0\" encoding=\"utf-8\"?><configuration><packageSources><add key=\"nuget.org\" value=\"https://api.nuget.org/v3/index.json\" protocolVersion=\"3\" /><add key=\"github\" value=\"https://nuget.pkg.github.com/arundo/index.json\" /></packageSources><packageSourceCredentials><github><add key=\"Username\" value=\"usernameNotReallyRequired\" /><add key=\"ClearTextPassword\" value=\"${{ inputs.nuget-token }}\" /></github></packageSourceCredentials></configuration>"
    
    
    - name: Login to Azure
      uses: Azure/login@v1
      with:
        creds: '{"clientId":"${{ inputs.client-id }}","clientSecret":"${{ inputs.client-secret }}","subscriptionId":"${{ inputs.subscription-id }}","tenantId":"${{ inputs.tenant-id }}"}'

    - name: Calculate github short sha
      id: short-sha
      run: echo "::set-output name=short-sha::$(git rev-parse --short HEAD)"
      shell: bash
